#!/usr/bin/env bash

set -euo pipefail

setup() {
  cwd=; cwd="$(cd "$(dirname "$0")" && pwd)"
}

source_deps() {
  . "${cwd}/github_actions.sh"
}

run() {
  local changes
  if ! changes=$(npm run -s genchanges -- -u); then
    exit 1
  fi

  changes="${changes:-No changes.}"

  set_output changes "${changes}"
}

main() {
  setup
  source_deps
  run "$@"
}

main "$@"
