#!/usr/bin/env bash

set -euo pipefail

run() {
  if [[ "${GITHUB_ACTIONS:-}" != 'true' ]]; then
    exit 0
  fi

  local committer_name='GitHub'
  local committer_email='noreply@github.com'

  git config user.name "${committer_name}"
  git config user.email "${committer_email}"
}

main() {
  run "$@"
}

main "$@"
