#!/usr/bin/env bash

set -euo pipefail

setup() {
  cwd=; cwd="$(cd "$(dirname "$0")" && pwd)"
}

source_deps() {
  . "${cwd}/github_actions.sh"
}

run() {
  if [[ "${GITHUB_ACTIONS:-}" != 'true' ]]; then
    exit 0
  fi

  local project_root; project_root=$(git rev-parse --show-toplevel)
  local manifest_path="${project_root}/package.json"
  local next_version; next_version="$(jq -r .version < "${manifest_path}")"
  local uid; uid="${GITHUB_RUN_ID:-0}-${GITHUB_RUN_NUMBER:-0}-$(date +%s)"

  if [[ -z "${next_version:-}" ]]; then
    exit 1
  fi

  local branch="release/v${next_version}-${uid}"

  set_output branch "${branch}"
  set_output title "Release v${next_version}"
  set_output commit-message "chore(release): v${next_version}"
}

main() {
  setup
  source_deps
  run "$@"
}

main "$@"
